### ISSUE TITLE
rpc.invoke signature suggested improvements 

### ISSUE THREAD

**Issue by bd82** [SAP/vscode-webview-rpc-lib#14]
The current signature is one of:

```typescript
       invoke(method: string, params?: any): Promise<any>;
       invoke(method: string, params?: any[]): Promise<any>;
```

- Support **Generics** so I won't have to write code such as:
  - ```typescript
            const initialData = this.rpc.invoke("onFrontendReady", []);
            this.updateData(initialData as unknown as PersonDetails);
    ```

- Accept variable argument list instead of an array of params, this way end users won't have to explicitly remember to wrap in an array.
  - ```typescript
        function invoke(method:string, ...params:any[]) {}
    ```
  - This will be a **breaking change** which will require publishing a new major version

**Comment by alex-gilin** [comment]
[PR](https://github.com/SAP/vscode-webview-rpc-lib/pull/490)
